/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItemsRouteRouteImport } from './routes/items/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ItemsIdRouteImport } from './routes/items/$id'

const ItemsRouteRoute = ItemsRouteRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRouteRoute,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteRouteWithChildren
  '/items/$id': typeof ItemsIdRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items/$id': typeof ItemsIdRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteRouteWithChildren
  '/items/$id': typeof ItemsIdRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items' | '/items/$id' | '/items/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items/$id' | '/items'
  id: '__root__' | '/' | '/items' | '/items/$id' | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRouteRoute: typeof ItemsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRouteRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRouteRoute
    }
  }
}

interface ItemsRouteRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

const ItemsRouteRouteChildren: ItemsRouteRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}

const ItemsRouteRouteWithChildren = ItemsRouteRoute._addFileChildren(
  ItemsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRouteRoute: ItemsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
